### ISSUE TITLE
Couldn't build the Image

### ISSUE THREAD

**Issue by Mohamad1994HD** [itlab-vision/dl-benchmark#192]
Host: Ubuntu18.04
OpenVINO: 2020 LTS version
When building with docker as mentioned, it brakes when building dependencies.

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l_y1pacb/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6trk24u_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-l_y1pacb/grpcio/
Error on or near line 92; exiting with status 1
The command '/bin/sh -c ./install_prerequisites.sh' returned a non-zero code: 1
`
What is the tested OpenVINO version? so I could reproduce the system

**Comment by KchnKchn** [comment]
@Mohamad1994HD, our system currently support OpenVINO 2020.2 version. Support for OpenVINO 2020.3 LTS 2020.4 and 2020.5 releases in progress

**Comment by Mohamad1994HD** [comment]
So i will rebuild it with OpenVINO 2020.2 and confirm it to you asap
