### ISSUE TITLE
Использование benchmark_app из состава OpenVINO

### ISSUE THREAD

**Issue by ilya-naumov** [itlab-vision/dl-benchmark#276]
В данный момент dl_benchmark измеряет производительность OpenVINO через внутренние скрипты (`inference_async_mode.py` и т.д.), при этом в состав OpenVINO включён специальный инструмент benchmark_app для [C++](https://github.com/openvinotoolkit/openvino/tree/2022.2.0/samples/cpp/benchmark_app) и [Python](https://github.com/openvinotoolkit/openvino/tree/2022.2.0/tools/benchmark_tool).    
Его использование для замеров даёт следующие преимущества:
1. Не нужно адаптировать код к изменениям в OpenVINO API.
1. Легко задействовать новые возможности (например [performance hints](https://github.com/openvinotoolkit/openvino/tree/2022.2.0/tools/benchmark_tool#performance-hints-latency-and-throughput))
1. Большое количество различных опций и метрик

Мы предлагаем добавить в dl_benchmark поддержку benchmark_app (для Python и С++) и готовы это реализовать. Старый функционал будет сохранен.

**Comment by valentina-kustikova** [comment]
@ilya-naumov, изначальная цель была уйти от использования встроенных инструментов OpenVINO, поскольку ориентировались на измерение производительности не только OpenVINO, но и других фреймворков для вывода, чтобы можно было делать сравнение производительности и открыто публиковать воспроизводимые результаты. Все-таки мы исследовательская группа. В случае, если вы планируете смотреть производительность только OpenVINO, то смысл нашего инструмента вообще теряется, поскольку вы можете напрямую использовать benchmark_app. Если же вы планируете сравнивать разные фреймворки, то необходим один инструмент, который заведомо одинаково считает метрики, а писать в статьях, что вывод с помощью OpenVINO мерился benchmark_app, а вывод других фреймворков с помощью нашего инструмента, в принципе недопустимо.

**Comment by nberezina** [comment]
@valentina-kustikova Мы хотим расширить функциональность текущего инструмента, добавить возможность использования нативных инструментов openVINO, предыдущий функционал оставить рабочим. Таким образом, в инструменте будет покрыто использование С++ и python API, с нашей точки зрения от расширения функционала таким образом, инструмент dl_benchmark только выиграет, так как будет предоставлять более полный набор функций.
На текущий момент мы планируем запускать бенчмарки на openvino и onnxruntime фреймворках с использованием разного железа, строить тренды от релиза к релизу, сравнивать и так далее, то есть использовать текущий инструмент в цикле разработки нужного нам продукта.
Мы понимаем, что для сравнения разных фреймворков нужны инструменты, которые измеряют производительность одинаковым способом и уже работаем над этим.
Также мы понимаем, что текущий функционал нужен вам в академических целях, и будем стараться его максимально сохранять.

**Comment by valentina-kustikova** [comment]
@nberezina, не возражаю на расширении, просто хотелось бы понимать ваши цели, чтобы сохранить целостность проекта и понимание, что и зачем. Спасибо за пояснение.

**Comment by nberezina** [comment]
implemented in PR https://github.com/itlab-vision/dl-benchmark/issues/277
