### ISSUE TITLE
Smoke test proposal

### ISSUE THREAD

**Issue by zmaslova** [itlab-vision/dl-benchmark#277]
Привет. Оказывается, в рамках рефакторинга, была внесена бага - если в конфиге был InferenceFramework TF, то запуск inference_benchmark.py падал с ошибкой (если запускать модель через inference_tensorflow.py - всё ок)
Бага пофикшена, PR сегодня пришлём.
Есть предложение добавить smoke test в ваш публичный репозиторий. Это будет быстрый скрипт на коротком конфиге, который просто проверяет, что inference_benchmark не падает на конфиге с разными InferenceFramework и моделями из разных фреймворков. Такой smoke test позволит избегать в дальнейшем подобных проблем.
Если против-оставим такой тест у себя в приватном репозитории.

cc @vladimir-dudnik

**Comment by valentina-kustikova** [comment]
@vladimir-dudnik, @zmaslova, поддерживаю. Мы планировали на этот год сделать тесты и демо.

**Comment by vladimir-dudnik** [comment]
@valentina-kustikova отлично, вместе мы многое сможем!

**Comment by nberezina** [comment]
implemented in PR https://github.com/itlab-vision/dl-benchmark/pull/284

**Comment by zmaslova** [comment]
Implemented and merged to master branch
