### ISSUE TITLE
Field delimeter in csv reports

### ISSUE THREAD

**Issue by nberezina** [itlab-vision/dl-benchmark#281]
We have been able to collect performance data using dl_benchmark  tool, but we have noticed one major inconvinience about csv-reports.
Fields are separated by ';' and it can't be changed. In excel default separator is ',' (at least for english version) and when user tries to open  csv file with excel, the layout is messed up, especially if data contains comma sign.
Also, code analysis showed that csv files are written string-by-string which is extremely hard to maintain and keep consistent

We have several proposals to solve this situation 
- leave format as is, but change file extension to .txt in order to use data importer in excel and set needed delimeter manually (cheap)
- replace ';' to ',' in current implementation (more expensive, but undesirable since its hard to maintain)
- create csv handler which will handle csv files using python buit-in csv module and have configurable delimeter (expencive but healthy way)

We'd like to discuss these options, and we can handle the implementation of choosen alternative.

**Comment by valentina-kustikova** [comment]
@nberezina, разделитель `;` используется по той причине, что полная информация о тестовой инфраструктуре содержит `,` в качестве разделителя, поэтому такая замена приведет к ситуации, когда csv-файл будет открыт средствами Excel некорректно. Если необходимо просматривать результаты бенчмаркинга с использованием Excel, то у нас есть конвертер из csv в xlsx, который позволяет построить удобную для восприятия табличку (пример такой таблички с результатам есть в репозитории `openvino-dl-benchmark\results\benchmarking\OpenVINO-2021.4-20-04-2022.xlsx`). Насколько я знаю, тип разделителя зависит от языка системы, поэтому по-хорошему надо определять язык и в зависимости от языка использовать в качестве разделителя `;` (Ru) или `,` (Eng). Думаю, что технически это можно реализовать, но такое решение не избавляет от проблемы наличия запятых в информации об инфраструктуре. 

Первый путь выглядит странно, потому что технически сохранить можно как txt-файл, но содержательно это csv-файл, поскольку csv-файл может содержать любой разделитель, не обязательно `,` или `;`.
Второй и третий пути приводят к проблеме наличия запятых в информации об инфраструктуре. Может, у вас есть какие-то предложения, каким образом обойти эту проблему.

**Comment by nberezina** [comment]
@valentina-kustikova стандартная библиотека csv заключает такие строки в кавычки. вот мой результат эксперимента с разделителями
```
line = {'a': 1, 'b': '1;2', 'c': '3'}
with open(r"1.csv", mode='w', newline='') as f:
    data = csv.DictWriter(f, fieldnames=line.keys(), delimiter=';')
    data.writerow(line)
```
 На выходе получаем файл 
` 1;"1;2";3
`
и excel его открывает валидно 
![image](https://user-images.githubusercontent.com/42569258/197831283-2f76d664-3af7-497c-86c6-6db585c0fd22.png)

Предложение переименовать файл в txt имеет смысл чтобы при открытии с помощью excel была возможность выбрать разделитель через import text wizard.
В целом, самое здоровое решение - это использовать библиотеку csv, тем более что она идет из коробки, чем построчно писать csv используя strings. В крайнем случае, можно delimiter параметризовать и иметь ключ, который позволяет это регулировать.

**Comment by valentina-kustikova** [comment]
@nberezina, да, поняла. По смыслу стандартная библиотека по умолчанию должна писать с тем разделителем, который соответствует версии системы.

@a-sidorova, есть ли какие-то препятствия, чтобы использовать стандартную библиотеку? Сможете оперативно внести изменения (выглядит не очень сложно)?

**Comment by nberezina** [comment]
@valentina-kustikova наша команда может сделать изменения.

**Comment by valentina-kustikova** [comment]
> @valentina-kustikova наша команда может сделать изменения. Назначьте пожалуйста issue на меня, если вы не против.

@nberezina, ок.
