### ISSUE TITLE
inference_benchmark.py script always returs code 0

### ISSUE THREAD

**Issue by nberezina** [itlab-vision/dl-benchmark#282]
We have noticed that  [inference_benchmark.py](https://github.com/itlab-vision/dl-benchmark/blob/master/src/benchmark/inference_benchmark.py) script always returns error code 0. 
Is it intended behavior? 
This approach can complicate troubleshooting when integrate this tool to CI.

Our suggestion is to modify code to return 1 if exception happened during inference and print a proper traceback.

We can handle the implementation as well.

**Comment by nberezina** [comment]
Yes it is. And it indicates success even if inference is actually failed

**Comment by valentina-kustikova** [comment]
@nberezina, согласна с точки зрения CI здесь будут проблемы. Если есть возможность внести соответствующие изменения, с нашей стороны возражений нет.

**Comment by brmarkus** [comment]
@nberezina Do you have specific requirements for different, detailed error-codes, or just "zero==success (including no object detected, nothing was classified, just without any errors occurring)" and "non-zero==something failed"?

**Comment by nberezina** [comment]
@brmarkus zero-nonzero works fine for us.

**Comment by nberezina** [comment]
@valentina-kustikova will come up with PR. please assign the issue to me for implementation.
