### ISSUE TITLE
src/benchmark/processes.py spliting into package

### ISSUE THREAD

**Issue by nberezina** [itlab-vision/dl-benchmark#283]
the file src/benchmark/processes.py is overloaded with fucntionality, especially considering addition of openvino python and c++ benchmark launchers.
Our suggestion is to split this file to separate files and handle them as package.
we can have a 'frameworks' package containing sub-folders for openvino, tensorflow, intel caffe processes, and in near future - onnxruntime. 
A factory/registry pattern will be used to create needed objects.
Such approach will simplify code maintenance and addition of new launchers.

We can handle the refactoring as well.

**Comment by valentina-kustikova** [comment]
@nberezina, поддерживаю.

**Comment by nberezina** [comment]
@valentina-kustikova назначьте на меня issue пожалуйста
