### ISSUE TITLE
Failed Smoke tests

### ISSUE THREAD

**Issue by a-sidorova** [itlab-vision/dl-benchmark#287]
После мержа [PR](https://github.com/itlab-vision/dl-benchmark/pull/284) падают новые Smoke tests с ошибкой:
`[ ERROR ] 'AsyncOpenVINOProcess' object has no attribute '_my_executor'`

[Logs](https://github.com/itlab-vision/dl-benchmark/actions/runs/3335296811/jobs/5519122962)

@nberezina

**Comment by nberezina** [comment]
@a-sidorova 
да, у нас такая же проблема в форке почему-то. пришлем ПР очень скоро, почему-то гитхаб неправильно промержил.

**Comment by nberezina** [comment]
Должно починиться с https://github.com/itlab-vision/dl-benchmark/pull/288/files
пожалуйста, убедитесь что smoke запустились, вероятно, потребуется нажать approve

**Comment by valentina-kustikova** [comment]
@nberezina, @a-sidorova, тесты прошли, залила изменения в master.

**Comment by a-sidorova** [comment]
@nberezina  @valentina-kustikova Спасибо! Но теперь в мастере только Code style проверяется. Smoke-tests должны запускаться только на пре-коммите? Или все-таки еще на пост-коммите?

**Comment by nberezina** [comment]
smoke должны запускаться на pull-request, судя по логу они запустились. мы в PR убрали чеки на push, чтобы не вылезти за ограничения гитхаб.
вот лог проверок от PR
https://github.com/itlab-vision/dl-benchmark/pull/288/checks

**Comment by valentina-kustikova** [comment]
@nberezina, @a-sidorova, они запустились после approve изменений. Обе проверки на coding style и smoke tests были успешными.

**Comment by a-sidorova** [comment]
@nberezina спасибо!

@valentina-kustikova я имела в виду, должны ли запускаться Smoke tests на самом мастере, а не только в Pull Request. Ответ от Натальи я получила, поэтому можно закрывать issue 😃 

![image](https://user-images.githubusercontent.com/43129309/198241514-69e6fca2-ed8c-4998-8bd0-2db1779436ff.png)
