### ISSUE TITLE
Создать Wiki для проекта

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#306]
@nberezina, @zmaslova, @a-sidorova, добрый день! Набросала структуру wiki для проекта, некоторые страницы заполнила информацией на основании того, что у нас есть в директории `docs` и в основном readme. Посмотрите, пожалуйста, то, что получилось. Несколько комментариев:
1. Мануал для нашего проекта на русском (сценарий с OpenVINO) ожидаем в ближайшее время, поэтому переведу и залью позднее.
2. Инструкцию по сборке перенесу из основного readme тоже немного позднее.
3. Также по готовности приведу в соответствие состояние репозитория, удалив файлы из папки docs, почистив основной readme. Также возможно переведу какие-то readme.

**Comment by zmaslova** [comment]
cc @vladimir-dudnik

**Comment by nberezina** [comment]
@valentina-kustikova я нашла способ открывать html  файлы в виде таблицы.
Можно посмотреть в моем форке https://nberezina.github.io/dl-benchmark/results/benchmarking/OpenVINO-2021.4-20-04-2022.html
Достигается с помощью github pages, и github actions, вот конфигурация. Для того, чтобы открыть файл, нужно знать к нему полный путь. В дальнейшем можно придумать какой-нибудь сводный  index.html с таблицами и он поднимется в качестве заглавной страницы сайта.
Вот конфигурация.
https://github.com/nberezina/dl-benchmark/blob/master/.github/workflows/static.yml
Если такой вариант устроит, то пришлю PR.
