### ISSUE TITLE
Реализация вывода для TF lite падает для некоторых моделей из OMZ на пачке, больше 1

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#339]
Обнаружила проблему в реализации вывода TF lite. Проблема состоит в следующем.

1. Загружаю некоторые tflite-модели из OMZ, а именно модели группы mobilenet-*. Я не конвертирую модели из формата pb в tflite, использую те, что загружены. Проблема не воспроизводится для модели inception_resnet_v2.tflite.

1. Запускаю вывод с использованием имеющейся реализации на пачке изображений размера 1. Вывод успешно отрабатывает. Код, который запускаю лежит по [ссылке](https://github.com/valentina-kustikova/dl-benchmark/tree/tflite-inference/src/inference). Это принесенный код + я дописала вывод результатов инференса.

1. Запускаю те же модели на пачке размера 3. Вывод падает с идентичной ошибкой (приведена ниже).

   ```
   tensorflow/lite/kernels/reshape.cc:85 num_input_elements != num_output_elements (3003 != 1001)Node number 29 (RESHAPE) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.
   ```
   При запуске использую следующие командные строки (предыдущий запуск отличается только размером пачки):

   ```bash
   python inference_tensorflowlite.py --model mobilenet_v1_1.0_224.tflite --input data/ --batch_size 3 --task classification --output_names output --labels labels/image_net_synset_first_class_base.txt --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375]

   python inference_tensorflowlite.py --model mobilenet_v2_1.0_224.tflite --input data/ --batch_size 3 --task classification --output_names output --labels labels/image_net_synset_first_class_base.txt --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375]

   python inference_tensorflowlite.py --model mobilenet_v2_1.4_224.tflite --input data/ --batch_size 3 --task classification --output_names output --labels labels/image_net_synset_first_class_base.txt --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375]
   ```

Аналогичная проблема у меня наблюдается на моделях EfficientNet-*, загруженных из [TF hub](https://tfhub.dev/s?dataset=imagenet-ilsvrc-2012-cls,imagenet&deployment-format=lite&module-type=image-classification).

Также попробовала конвертировать inception_v3_2016_08_28_frozen.pb из OMZ имеющимся конвертером (командная строка ниже), запуск на пачке, превышающей 1, приводит к той же ошибке. 

```bash
python tflite_converter.py --model-path googlenet-v3/inception_v3_2016_08_28_frozen.pb --source-framework tf
```

Подскажите, пожалуйста, чем вызвана эта проблема?

Спасибо!

**Comment by n-berezina-nn** [comment]
@valentina-kustikova 

tflite модели mobilenet-* и EfficientNet-* и inception_v3_2016_08_28_frozen.pb сохранены в омз со статическим batch=1, при запуске с batch > 1 tflite не может изменить размеры входов/выходов для операции reshape.
Для mobilenet можно использовать загруженные omz_downloader .pb файлы (они сохранены с динамическим батчом) и tflite_converter:

`python tflite_converter.py --model-path mobilenet_v1_1.0_224_frozen.pb --input-names input --output-names MobilenetV1/Predictions/Reshape_1 --source-framework tf`

**Comment by valentina-kustikova** [comment]
@n-berezina-nn, спасибо!

Попробовала запустить mobilenet-модели. Для mobilenet-v1-1.0.-224 все сработало и вывод запустился на пачке >1, для остальных mobilenet-моделей получила следующие ошибки.

Командные строки конвертации для моделей v2:
```bash
python tflite_converter.py --model-path mobilenet_v2_1.0_224_frozen.pb --input-names input --output-names MobilenetV2/Predictions/Reshape_1 --source-framework tf

python tflite_converter.py --model-path mobilenet_v2_1.4_224_frozen.pb --input-names input --output-names MobilenetV2/Predictions/Reshape_1 --source-framework tf
```
Идентичная ошибка для обеих моделей:
```
2023-03-20 14:17:33.993910: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:2046] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexConv2D
Details:
        tf.Conv2D(tensor<*xf32>, tensor<3x3x3x32xf32>) -> (tensor<?x?x?x32xf32>) : {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "SAME", strides = [1, 2, 2, 1], use_cudnn_on_gpu = true}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
```

Командные строки конвертации для моделей v3:
```bash
python tflite_converter.py --model-path mobilenet_v3_small_224_1.0_float.savedmodel/saved_model.pb --source-framework tf

python tflite_converter.py --model-path mobilenet_v3_large_224_1.0_float.savedmodel/saved_model.pb --source-framework tf
```
Идентичная ошибка для обеих моделей:
```
[ INFO ] Loading TF model
Traceback (most recent call last):
  File "tflite_converter.py", line 341, in <module>
    main()
  File "tflite_converter.py", line 329, in main
    model = load_model(model_path, args.input_names, args.output_names, args.freeze_constant_input, log)
  File "tflite_converter.py", line 282, in load_model
    model_graph = load_tf_model(model_path)
  File "tflite_converter.py", line 96, in load_tf_model
    model = load_pb_file(file)
  File "tflite_converter.py", line 72, in load_pb_file
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'
```

**Comment by JuliaKamelina** [comment]
@valentina-kustikova 
> Идентичная ошибка для обеих моделей:
2023-03-20 14:17:33.993910: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:2046] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexConv2D
Details:
        tf.Conv2D(tensor<*xf32>, tensor<3x3x3x32xf32>) -> (tensor<?x?x?x32xf32>) : {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "SAME", strides = [1, 2, 2, 1], use_cudnn_on_gpu = true}
See instructions: https://www.tensorflow.org/lite/guide/ops_select

Это не ошибка, это сообщение о том, что при конвертации применился Flex Delegate, и операция tf.Conv2D осталась в TF или частично сконвертировалась в TFLite. Модель при этом конвертируется. Во время инференса эта операция будет делегирована. Для запуска инференса еще понадобится указать параметр `--input_shapes input[1, 224, 224, 3]`. 

> Командные строки конвертации для моделей v3:

Mobilenet-v3 сохранены в формате saved_model, для них путь до модели это путь до папки с `saved_model.pb`, `variables` и `assets`, то есть `--model-path mobilenet_v3_small_224_1.0_float.savedmodel`.
Эти модели тоже сохранены с динамическим размером входа, для них при запуске инференса тоже понадобится указать размер через `--input_shapes`

**Comment by valentina-kustikova** [comment]
@JuliaKamelina, спасибо, все заработало. Обновите, пожалуйста, Readme с информацией по запуску `inference_tflite.py` на предмет соответствия аргументов со скриптом + надо дать какую-то минимальную информацию по делегатам, т.е. когда устанавливать и примеры значений, а то как-то сложно осознать, если с этим никогда не работал, что это и зачем.

@maslovaz, @n-berezina-nn

**Comment by FenixFly** [comment]
@JuliaKamelina помогите пожалуйста.

Запускаемся с размерами пачки 1,2,4,8,16,32,64

Эксперименты с размерами пачки 1,2,4 проходят, а остальные падают с ошибкой. Модели **mobilenet_v3_small**, **mobilenet_v3_large** и **mobilenet_v2_1.0_224** взяты из OMZ и сковертированы конвертором в нашем репозитории.

команда инференса
Command line is: python3 /home/itmm/dli-jenkins-worker/dl-benchmark/src/inference/inference_tensorflowlite.py -m /mnt/models_paper/tflite_models/mobilenet_v3_small_224_1.0_float.tflite -i /mnt/datasets/ImageNET/ -b 64 -d CPU -ni 1000 --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375] --input_shapes input_1[1,224,224,3] --layout NHWC --raw_output true

[ INFO ] Loading network files:
/mnt/models_paper/tflite_models/mobilenet_v3_small_224_1.0_float.tflite
[ INFO ] Shape for input layer input_1: 64x224x224x3
[ INFO ] Preparing input data
[ INFO ] Reshaping model input from [1 1 1 3] to [64, 224, 224, 3]
[ INFO ] Starting inference (1000 iterations)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[ ERROR ] Traceback (most recent call last):
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/inference/inference_tensorflowlite.py", line 319, in main
    result, inference_time = inference_tflite(interpreter, args.number_iter, io.get_slice_input)
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/inference/inference_tensorflowlite.py", line 184, in inference_tflite
    interpreter.set_tensor(input_info[name][0], data.astype(input_info[name][1]))
  File "/home/itmm/.local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 697, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
**ValueError: Cannot set tensor: Dimension mismatch. Got 0 but expected 64 for dimension 0 of input 0.**
Process returncode = 1

**Comment by FenixFly** [comment]
> @FenixFly такая проблема воспроизвелась при количестве изображений в датасете < числе итераций * размер пачки. [get_slice_input](https://github.com/itlab-vision/dl-benchmark/blob/master/src/inference/io_adapter.py#L135) возвращает пустой тензор

Спасибо, сейчас попробуем

**Comment by n-berezina-nn** [comment]
@FenixFly @valentina-kustikova подскажите, помогло ли решение?

**Comment by FenixFly** [comment]
@n-berezina-nn да, спасибо большое, оказалось что количество изображений в папке должно быть кратно размеру пачки (либо количество изображений в папке >= числе итераций * размер пачки)

**Comment by n-berezina-nn** [comment]
тогда закрываем issue
