### ISSUE TITLE
Запуск моделей MobileNet-v3-* через TensorFlow

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#346]
@n-berezina-nn, @maslovaz, нужна ваша помощь. Запускаю модели MobileNet-v3-large и MobileNet-v3-small из OMZ через TensorFlow, модели предварительно конвертирую с помощью `omz_converter`. Командная строка запуска ниже. В результате получаю `Error parsing message with type 'tensorflow.GraphDef'`. Подскажите, пожалуйста, в чем может быть проблема? Спасибо!

```bash
python inference_tensorflow.py --model mobilenet-v3-small-1.0-224-tf/mobilenet_v3_small_224_1.0_float.savedmodel/saved_model.pb --input data/ --batch_size 3 --input_shape 224 224 3 --task classification --number_top 5 --mean 127.5 127.5 127.5 --input_scale 127.5 --labels labels/image_net_synset_first_class_base.txt
```

**Comment by maslovaz** [comment]
mobilenet-v3-small-1.0-224-tf/mobilenet_v3_small_224_1.0_float.savedmodel (папка) - это saved_model формат, он должен грузится через tf.saved_model.load. поддержка тф моделей в этом формате есть только в tflite конвертере, в inference_tensorflow.py поддержки сейчас нет

**Comment by valentina-kustikova** [comment]
> mobilenet-v3-small-1.0-224-tf/mobilenet_v3_small_224_1.0_float.savedmodel (папка) - это saved_model формат, он должен грузится через tf.saved_model.load. поддержка тф моделей в этом формате есть только в tflite конвертере, в inference_tensorflow.py поддержки сейчас нет

Спасибо! Создам задачу, чтобы добавить поддержку запуска и таких моделей.
