### ISSUE TITLE
Добавить поддержку вывода моделей в формате saved_model через TensorFlow

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#349]
Модели в формате `saved_model` должны загружаться через tf.saved_model.load. Необходимо добавить поддержку загрузки таких моделей в `inference_tensorflow.py`.

**Comment by n-berezina-nn** [comment]
назначила на себя. работа в прогрессе

**Comment by n-berezina-nn** [comment]
сделано, PR https://github.com/itlab-vision/dl-benchmark/pull/389
