### ISSUE TITLE
Проблемы с заданием количества потоков для TFLite

### ISSUE THREAD

**Issue by FenixFly** [itlab-vision/dl-benchmark#362]
В TFLite предполагается возможно задать количество потоков (-nthreads). Сейчас возникают ошибки, и если задать этот параметр и через конфиг бенчмарка, и если запускать inference_tensorflow.py (разные ошибки). @maslovaz, посмотрите пожалуйста.

**Comment by valentina-kustikova** [comment]
@FenixFly, может, ты имеешь ввиду inference_tensorflowlite.py?

@FenixFly, можешь бросить список командная строка и ошибка?

**Comment by maslovaz** [comment]
@FenixFly Создала ПР с фиксом
