### ISSUE TITLE
[PyTorch] WARNING:root:Error when printing inference results. 'AlexNet' object has no attribute 'name_or_path'

### ISSUE THREAD

**Issue by a-sidorova** [itlab-vision/dl-benchmark#424]
### Env
- torch==2.1.0
- torchvision==0.16.0

### How to reproduce
```
python3 inference_pytorch.py  -mm torchvision.models  -i /home/itmm/sidorova/openvino-dl-benchmark/results/validation/images/ILSVRC2012_val_00000023.JPEG,/home/itmm/sidorova/openvino-dl-benchmark/results/validation/images/ILSVRC2012_val_00000247.JPEG,/home/itmm/sidorova/openvino-dl-benchmark/results/validation/images/ILSVRC2012_val_00018592.JPEG --task classification --input_names data --input_shapes [1,3,224,224] --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375] -t classification -b 3 -mn alexnet
```

### Output
```
WARNING:root:Error when printing inference results. 'AlexNet' object has no attribute 'name_or_path'
```

После ребейза на мастер не могу провалидировать классификационные модели в PyTorch Python API. Использую ту же командную строку, что и раньше.

**Comment by valentina-kustikova** [comment]
@n-berezina-nn, @maslovaz, возникла проблема после последних изменений. Посмотрите, пожалуйста. Спасибо!

**Comment by maslovaz** [comment]
@a-sidorova проверила, не работает именно запуск на валидацию ( т.е. запуск с дефолтным числом итераций 1, с числом итераций 5 есть тест в смоках, и он проходит). смотрю, как можно пофиксить

**Comment by maslovaz** [comment]
@a-sidorova прошу проверить https://github.com/itlab-vision/dl-benchmark/pull/425
