### ISSUE TITLE
Не работает логирование через logging в скрипте вывода PyTorch

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#433]
По какой-то причине у нас с @a-sidorova в скрипте вывода PyTorch не работает стандартное логирование средствами logging. Признаки - на консоли просто нет ничего, но скрипт явно отрабатывает и записывает json-файл с метриками производительности. Пример команды запуска ниже, модель из OMZ.

```bash
python inference_pytorch.py --model_name resnet50 --weights /home/itmm/Documents/kustikova_v/public/resnet-50-pytorch/resnet50-19c8e357.pth --input /home/itmm/Documents/kustikova_v/data/ --labels labels/image_net_labels.json --batch_size 4 --input_names data --input_shapes data[4,3,224,224] -ni 1 --task classification --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375]
```

Смогла полечить это локально через перезагрузку пакета (ниже), но не выкладываю в основной репозиторий.

```bash
from importlib import reload
reload(log)
```

В скриптах вывода TensorFlow, MXNet, TensorFlow lite данная проблема не наблюдается. Делала со всеми пробные запуски.

**Comment by n-berezina-nn** [comment]
@valentina-kustikova укажите пожалуйста версию python  и приложите вывод pip freeze

**Comment by valentina-kustikova** [comment]
> @valentina-kustikova укажите пожалуйста версию python и приложите вывод pip freeze

```bash
Python 3.9.0
```

```bash
addict==2.4.0
certifi==2023.7.22
charset-normalizer==3.3.2
defusedxml==0.7.1
filelock==3.13.1
fsspec==2023.10.0
idna==3.4
Jinja2==3.1.2
jstyleson==0.0.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.26.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
opencv-python==4.8.1.78
openvino==2023.1.0
openvino-dev==2023.1.0
openvino-telemetry==2023.2.1
Pillow==10.1.0
PyYAML==6.0.1
requests==2.31.0
scipy==1.10.1
sympy==1.12
texttable==1.7.0
torch==2.1.0
torchaudio==2.1.0
torchvision==0.16.0
tqdm==4.66.1
triton==2.1.0
typing_extensions==4.8.0
urllib3==2.0.7
```

**Comment by n-berezina-nn** [comment]
@valentina-kustikova в pytorch  конфигурируется logging должным образом. Просто используется import logging as log. Это может давать такие сайд-эффекты.
Зафиксим это.

**Comment by valentina-kustikova** [comment]
@n-berezina-nn, спасибо!

**Comment by n-berezina-nn** [comment]
@valentina-kustikova можете попробовать с моего форка или с PR? https://github.com/itlab-vision/dl-benchmark/pull/441/files
Если Ваша проблема решится, то сделаю аналогичный фикс для остальных скриптов.

**Comment by valentina-kustikova** [comment]
> @valentina-kustikova можете попробовать с моего форка или с PR? https://github.com/itlab-vision/dl-benchmark/pull/441/files Если Ваша проблема решится, то сделаю аналогичный фикс для остальных скриптов.

@n-berezina-nn, клонировала ваш репозиторий и запустила скрипт инференса PyTorch, вывода на консоль по-прежнему нет. Запуск делаю в виртуальной среде, настройки присылала выше.

```bash
git clone https://github.com/n-berezina-nn/dl-benchmark/tree/master
cd dl-benchmark/src/inference/
python inference_pytorch.py --model_name resnet50 --weights /home/itmm/Documents/kustikova_v/public/resnet-50-pytorch/resnet50-19c8e357.pth --input /home/itmm/Documents/kustikova_v/data/ --labels labels/image_net_labels.json --batch_size 4 --input_names data --input_shapes data[4,3,224,224] -ni 1 --task classification --mean [123.675,116.28,103.53] --input_scale [58.395,57.12,57.375]
```

**Comment by n-berezina-nn** [comment]
@valentina-kustikova обновите пожалуйста репозиторий. следующая итерация )

**Comment by n-berezina-nn** [comment]
@valentina-kustikova да, решаю эту проблему сейчас и смоки тоже немного попадали.

**Comment by n-berezina-nn** [comment]
@valentina-kustikova PR https://github.com/itlab-vision/dl-benchmark/pull/441 можно смотреть

виноват вероятнее всего оказался logging.basicConfig

**Comment by valentina-kustikova** [comment]
> @valentina-kustikova PR #441 можно смотреть
> 
> виноват вероятнее всего оказался logging.basicConfig

@n-berezina-nn, проверила, работает, закрываю пулл-реквест. Спасибо!
