### ISSUE TITLE
ModuleNotFoundError: No module named 'src' in tflite_converter.py

### ISSUE THREAD

**Issue by akl-01** [itlab-vision/dl-benchmark#442]
Конвертировал модель из onnx формата в tflite по указанному примеру: 
`python tflite_converter.py --model-path <path/to/input/model> --source-framework <source_framework>`

В процессе конвертации получил ошибку:
```
Traceback (most recent call last):
  File "/home/arklykov/dl-benchmark/./src/model_converters/tf2tflite/tflite_converter.py", line 12, in <module>
    from src.model_converters.tensorflow_common import load_model  # noqa
ModuleNotFoundError: No module named 'src'
```

Кажется, достаточно в строке `from src.model_converters.tensorflow_common import load_model` удалить `src.model_converters`. Если это действительно так, внести, пожалуйста, изменения в репозиторий.

**Comment by valentina-kustikova** [comment]
@akl-01, дайте, пожалуйста, полную информацию о вашей инфраструктуре (pip freeze) и ссылку на модель, чтобы мы могли воспроизвести ошибку. Встречала аналогичную ошибку из-за низкой версии Python.

**Comment by FenixFly** [comment]
@akl-01 добрый день. Сегодня добавили фикс https://github.com/itlab-vision/dl-benchmark/pull/453
Пожалуйста проверьте воспроизводится ли проблема

**Comment by akl-01** [comment]
@FenixFly @valentina-kustikova добрый день! 
Извините за оставленный без ответа предыдущий вопрос.  
Сейчас все удалось сконвертировать, проблема решена, спасибо!
