### ISSUE TITLE
[RKNN] Необходимо обновить в README и на WIKI информацию про RKNN

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#470]
@n-berezina-nn, обнаружила, что нигде, кроме src/bencmark/README.md, нет информации. Необходимо обновить wiki-страницы + src/inference/README.md + корневой README.md.

**Comment by n-berezina-nn** [comment]
@valentina-kustikova сделаем изменения отдельным PR
