### ISSUE TITLE
[TVM] Описание экспериментов на x86

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#505]
@FenixFly, поправь, пожалуйста.

1. На Wiki-странице с точностью [https://github.com/itlab-vision/dl-benchmark/wiki/Accuracy](https://github.com/itlab-vision/dl-benchmark/wiki/Accuracy) надо описать, как получены модели, по аналогии с [https://github.com/itlab-vision/dl-benchmark/wiki/Performance](https://github.com/itlab-vision/dl-benchmark/wiki/Performance), а не просто указывать уровень оптимизации.
1. На странице [https://github.com/itlab-vision/dl-benchmark/wiki/Performance](https://github.com/itlab-vision/dl-benchmark/wiki/Performance) надо поправить ссылки с результатами экспериментов.

**Comment by FenixFly** [comment]
> @FenixFly, поправь, пожалуйста.
> 
>     1. На Wiki-странице с точностью https://github.com/itlab-vision/dl-benchmark/wiki/Accuracy надо описать, как получены модели, по аналогии с https://github.com/itlab-vision/dl-benchmark/wiki/Performance, а не просто указывать уровень оптимизации.
> 
>     2. На странице https://github.com/itlab-vision/dl-benchmark/wiki/Performance надо поправить ссылки с результатами экспериментов.

Исправил
