### ISSUE TITLE
Описание работы с DGL и Spektral на Wiki-страницах проекта

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#535]
@Atikin-NT, @ArchiMikael, необходимо подготовить краткое описание установки пакетов DGL и Spektral в раздел https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux и описание ресурсов, откуда брать модели, для раздела https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing. Поскольку у вас нет прямого доступа к вики-страницам, то напишите, пожалуйста, текст здесь, а я потом при необходимости поправлю и добавлю на вики. Спасибо!

**Comment by valentina-kustikova** [comment]
@Atikin-NT, @ArchiMikael, таска висит открытая. Просьба - сделать в течение этой недели.

**Comment by Atikin-NT** [comment]
### Для раздела [BuildingForLinux](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux)

**Python API**
To infer deep learning models using PyTorch, please, install the following packages:
```
# If you have installed dgl-cuXX package, please uninstall it first.
pip install  dgl -f https://data.dgl.ai/wheels/torch-2.1/repo.html
```

---

### Для раздела [ModelPreparing](https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing)

To infer DGL-models it is required to install the [PyTroch](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux#pytorch-pre-requisites) and [DGL](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux#dgl-pre-requisites) Python packages. From the model files, you must download a file in the PyTorch format (`.pt`, `.pth`) and a `.py` file with a description of the architecture. [This](https://github.com/itlab-vision/itlab-vision-dl-benchmark-models/tree/main/dgl/models/classification/GCN) repository provides an example of the described files.

**Comment by valentina-kustikova** [comment]
> ### Для раздела [BuildingForLinux](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux)
> **Python API** To infer deep learning models using PyTorch, please, install the following packages:
> 
> ```
> # If you have installed dgl-cuXX package, please uninstall it first.
> pip install  dgl -f https://data.dgl.ai/wheels/torch-2.1/repo.html
> ```
> 
> ### Для раздела [ModelPreparing](https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing)
> To infer DGL-models it is required to install the [PyTroch](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux#pytorch-pre-requisites) and [DGL](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux#dgl-pre-requisites) Python packages. From the model files, you must download a file in the PyTorch format (`.pt`, `.pth`) and a `.py` file with a description of the architecture. [This](https://github.com/itlab-vision/itlab-vision-dl-benchmark-models/tree/main/dgl/models/classification/GCN) repository provides an example of the described files.

@Atikin-NT, спасибо, обновила разделы.

**Comment by ArchiMikael** [comment]
Для [BuildingForLinux](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux):

If you would like to infer deep models using [Spektral](https://graphneural.network/), please, install spektral package using pip.
```
pip install spektral
``` 
---

Для [ModelPreparing](https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing):

Spektral uses keras save/load system implemented in newer versions of Tensorflow using special `.keras` file format. Additionaly, `.py` file with used GNN class is required. Examples can be thound in [this](https://github.com/ArchiMikael/SpektralModels) repository.

**Comment by valentina-kustikova** [comment]
> Для [BuildingForLinux](https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux):
> 
> If you would like to infer deep models using [Spektral](https://graphneural.network/), please, install spektral package using pip.
> 
> ```
> pip install spektral
> ```
> 
> Для [ModelPreparing](https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing):
> 
> Spektral uses keras save/load system implemented in newer versions of Tensorflow using special `.keras` file format. Additionaly, `.py` file with used GNN class is required. Examples can be thound in [this](https://github.com/ArchiMikael/SpektralModels) repository.

@ArchiMikael, спасибо! Единственный вопрос - почему ссылка на ваш репозиторий, а не в https://github.com/itlab-vision/itlab-vision-dl-benchmark-models/tree/main/spektral? Если вы не перенесли модели, то перенесите, пожалуйста, в репозиторий проекта, потому что есть шансы, что через пару лет вы можете удалить ваш репозиторий.

**Comment by ArchiMikael** [comment]
Извините, забыл в прошлом семестре залить файлы моделей туда. Сейчас всё загрузил и изменил ссылку.
