### ISSUE TITLE
Обновление информации о поддержке PaddlePaddle на Wiki-страницах

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/dl-benchmark#558]
@IgorKonovalovAleks, необходимо добавить информацию на страницы [https://github.com/itlab-vision/dl-benchmark/wiki/BuildingForLinux] и [https://github.com/itlab-vision/dl-benchmark/wiki/ModelPreparing] по аналогии с другими фреймворками.

**Comment by IgorKonovalovAleks** [comment]
Это в BuildingFor Linux:
To infer deep learning models using PaddlePaddle, please, install the following packages:
CPU version : If you only want to install CPU version, please refer to command below

Command to install CPU version is:
`
python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
`
or
`
python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
`
GPU version : If you only want to install GPU version, please refer to command below

Note:

You need to confirm that your GPU meets the requirements listed above
`
python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple
`
or
`
python -m pip install paddlepaddle-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple
`

**Comment by IgorKonovalovAleks** [comment]
Downloading Inference Model
You can download the models directly from PaddleClas repository. The list of avilable models is avilable here:
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5.2/docs/en/models/index.rst
The command for downloading Paddle Inference Model is as follow:
```
cd deploy/models
# download the inference model and decompression
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/PPLCNet_x1_0_infer.tar && tar -xf PPLCNet_x1_0_infer.tar
```

After decompression, the directory models should be shown below.

├── PPLCNet_x1_0_infer
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
